package feedlist

import (
	"os"
	"strings"
	"testing"
)

// TestDummy ensures we can find a default directory
func TestDummy(t *testing.T) {

	obj := New("")

	if !strings.Contains(obj.filename, ".rss2email") {
		t.Fatalf("autogenerated filename doesn't have our expected substring")
	}
}

// TestEmpty ensures we can handle a missing file
func TestEmpty(t *testing.T) {

	obj := New("/path/does/not/exist")

	entries := obj.Entries()
	if len(entries) != 0 {
		t.Fatalf("Found error reading a missing file")
	}
}

// TestMissingHome ensures that we can find the home-directory
// of a user, even without the environment
func TestMissingHome(t *testing.T) {

	cur := os.Getenv("HOME")
	os.Setenv("HOME", "")

	obj := New("")

	if !strings.Contains(obj.filename, ".rss2email") {
		t.Fatalf("autogenerated filename doesn't have our expected substring")
	}

	// Reset
	os.Setenv("HOME", cur)
}
